export const SLOT_MIN = 0;
export const SLOT_MAX = 99;
export const MAX_TEXT_CHARS = 30_000;
export const MAX_FILE_BYTES = 10 * 1024 * 1024;
export const STORAGE_LIMIT_BYTES = 512 * 1024 * 1024;
export const UPLOAD_RESERVATION_BYTES = MAX_FILE_BYTES;
export const UPLOAD_CAPABILITY_SECONDS = 15 * 60;
export const DOWNLOAD_URL_SECONDS = 60;
export const STORAGE_BUCKET = "pb-v3";
